FROM node:20-alpine
RUN apk add --no-cache tzdata
RUN apk add --upgrade --no-cache vips-dev build-base --repository https://alpine.global.ssl.fastly.net/alpine/v3.10/community/

ENV TZ Europe/Amsterdam
RUN cp /usr/share/zoneinfo/${TZ} /etc/localtime
RUN echo ${TZ} > /etc/timezone

# copy contents of directory to /app/
WORKDIR /app
COPY . .

# install packages
RUN npm ci

# Accept build arguments from CapRover
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_EMAILJS_PUBLIC_KEY
ARG NEXT_PUBLIC_EMAILJS_SERVICE_ID
ARG NEXT_PUBLIC_EMAILJS_TEMPLATE_ID
ARG NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ARG EMAILJS_PRIVATE_KEY
ARG RECAPTCHA_SECRET_KEY
ARG BOL_API_CLIENT_ID
ARG BOL_API_CLIENT_SECRET
ARG BOL_PRODUCT_FEED_USERNAME
ARG BOL_PRODUCT_FEED_PASSWORD
ARG ADMIN_PASSWORD
ARG DATABASE_URL

# Convert build arguments to environment variables for the build process
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_EMAILJS_PUBLIC_KEY=$NEXT_PUBLIC_EMAILJS_PUBLIC_KEY
ENV NEXT_PUBLIC_EMAILJS_SERVICE_ID=$NEXT_PUBLIC_EMAILJS_SERVICE_ID
ENV NEXT_PUBLIC_EMAILJS_TEMPLATE_ID=$NEXT_PUBLIC_EMAILJS_TEMPLATE_ID
ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY=$NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ENV EMAILJS_PRIVATE_KEY=$EMAILJS_PRIVATE_KEY
ENV RECAPTCHA_SECRET_KEY=$RECAPTCHA_SECRET_KEY
ENV BOL_API_CLIENT_ID=$BOL_API_CLIENT_ID
ENV BOL_API_CLIENT_SECRET=$BOL_API_CLIENT_SECRET
ENV BOL_PRODUCT_FEED_USERNAME=$BOL_PRODUCT_FEED_USERNAME
ENV BOL_PRODUCT_FEED_PASSWORD=$BOL_PRODUCT_FEED_PASSWORD
ENV ADMIN_PASSWORD=$ADMIN_PASSWORD
ENV DATABASE_URL=$DATABASE_URL

# build the Next.js app with environment variables available
RUN npm run build

# run
EXPOSE 3000

ENV HOSTNAME=0.0.0.0
ENV PORT=3000

# Copy and use startup script that runs migrations before starting
RUN chmod +x /app/start.sh

CMD [ "/app/start.sh" ]